<?php
namespace  frontend\widgets;

use backend\models\GoodsCategory;
use yii\base\Widget;

class CategoryWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
       $redis=new \Redis();
       $redis->connect('127.0.0.1');
       $category_html=$redis->get('category_html');
       if($category_html==null){
           $goods_categories = GoodsCategory::findAll(['parent_id'=>0]);
           $category_html = $this->renderFile('@app/widgets/view/category.php',['goods_categories'=>$goods_categories]);

            $redis->set('category_html',$category_html);
           // $redis->expire()

        }
           return $category_html;
    }


}


?>